Staff:
  co-owner: OhLookItsJay
Developers:
  - fuck
  - shit
  - bitch
  - ass
  - arse
  - arsehole
  - cunt
  - asshole
Admins:
  - fuck
  - shit
  - bitch
  - ass
  - arse
  - arsehole
  - cunt
  - asshole
Moderators:
  - fuck
  - shit
  - bitch
  - ass
  - arse
  - arsehole
  - cunt
  - asshole
Builders:
  - fuck
  - shit
  - bitch
  - ass
  - arse
  - arsehole
  - cunt
  - asshole
Helpers:
  - fuck
  - shit
  - bitch
  - ass
  - arse
  - arsehole
  - cunt
  - asshole
General:
  self-cleared: '''You have successfully cleared your chat!'''
Ranks:
  Knight:
    Cost: $90,000
    Name: Knight
  Duke:
    Cost: $175,000
    Name: Duke
  Baron:
    Cost: $225,000
    Name: Baron
  Regent:
    Cost: $350,000
    Name: Regent
  Prince:
    Cost: $550,000
    Name: Prince
  King:
    Cost: $1,500,000
    Name: King
  Emperor:
    Cost: $3,500,000
    Name: Emperor
  GrandMaster:
    Cost: $7,000,000
    Name: GrandMaster
  Overlord:
    Cost: $10,000,000
    Name: Overlord
Website:
  URL: http://trintoncraft.com
  Donate-URL: http://store.trintoncraft.com
Developers:
  - fuck
  - shit
  - bitch
  - ass
  - arse
  - arsehole
  - cunt
  - asshole